import type {
  WeaponDefinition,
  WeaponProjectileSpawn,
  WeaponVisualSettings,
} from '../weapons/WeaponTypes.ts'

export const HITSCAN_RIFLE_VISUALS: WeaponVisualSettings = {
  impactAccentColor: '#fff0bd',
  impactColor: '#ff6b4a',
  impactGlowColor: '#ffd8a8',
  impactLifetimeMs: 120,
  impactRingSize: 0.32,
  impactSparkLength: 0.16,
  impactSparkWidth: 0.02,
  impactSize: 0.12,
  muzzleFlashColor: '#ffe08a',
  muzzleFlashDistance: 0.02,
  muzzleFlashGlowColor: '#fff5c8',
  muzzleFlashLength: 0.3,
  muzzleFlashLifetimeMs: 50,
  muzzleFlashLightDistance: 4.6,
  muzzleFlashLightIntensity: 1.3,
  muzzleFlashSecondaryColor: '#ffd15d',
  muzzleFlashSize: 0.14,
  muzzleFlashSparkColor: '#ffffff',
  tracerColor: '#fff0b3',
  tracerGlowColor: '#fff8df',
  tracerGlowThickness: 0.09,
  tracerLifetimeMs: 58,
  tracerThickness: 0.034,
  tracerTipColor: '#ffffff',
  tracerTipSize: 0.034,
}

export const HITSCAN_RIFLE_DEFINITION: WeaponDefinition = {
  cooldownSeconds: 0.11,
  damage: 30,
  displayName: 'Rifle',
  fireType: 'hitscan',
  id: 'rifle',
  maxDistance: 160,
  visuals: HITSCAN_RIFLE_VISUALS,
}

export const SHOTGUN_PELLET_PATTERN: ReadonlyArray<readonly [number, number]> = [
  [0, 0],
  [-0.62, 0.12],
  [0.62, 0.12],
  [-0.18, -0.52],
  [0.18, -0.52],
  [-0.82, -0.28],
  [0.82, -0.28],
  [0, 0.72],
]

export const HITSCAN_SHOTGUN_PELLET_DAMAGE = 14
export const HITSCAN_SHOTGUN_SPREAD_ANGLE_DEGREES = 4.8
export const HITSCAN_SHOTGUN_VISUALS: WeaponVisualSettings = {
  impactAccentColor: '#fff2c0',
  impactColor: '#ff8f52',
  impactGlowColor: '#ffd7a1',
  impactLifetimeMs: 145,
  impactRingSize: 0.42,
  impactSparkLength: 0.22,
  impactSparkWidth: 0.028,
  impactSize: 0.17,
  muzzleFlashColor: '#ffb703',
  muzzleFlashDistance: 0.03,
  muzzleFlashGlowColor: '#ffe8a5',
  muzzleFlashLength: 0.48,
  muzzleFlashLifetimeMs: 82,
  muzzleFlashLightDistance: 5.6,
  muzzleFlashLightIntensity: 1.7,
  muzzleFlashSecondaryColor: '#ff8f1f',
  muzzleFlashSize: 0.21,
  muzzleFlashSparkColor: '#fff4d1',
  tracerColor: '#ffd166',
  tracerGlowColor: '#fff2b2',
  tracerGlowThickness: 0.14,
  tracerLifetimeMs: 105,
  tracerThickness: 0.058,
  tracerTipColor: '#fff8dd',
  tracerTipSize: 0.052,
}

export const HITSCAN_SHOTGUN_DEFINITION: WeaponDefinition = {
  cooldownSeconds: 0.48,
  damage: HITSCAN_SHOTGUN_PELLET_DAMAGE * SHOTGUN_PELLET_PATTERN.length,
  displayName: 'Shotgun',
  fireType: 'hitscan',
  id: 'shotgun',
  maxDistance: 30,
  visuals: HITSCAN_SHOTGUN_VISUALS,
}

export const ROCKET_LAUNCHER_VISUALS: WeaponVisualSettings = {
  impactAccentColor: '#fff4d2',
  impactColor: '#ffb267',
  impactGlowColor: '#fff0c9',
  impactLifetimeMs: 0,
  impactRingSize: 0,
  impactSparkLength: 0,
  impactSparkWidth: 0,
  impactSize: 0,
  muzzleFlashColor: '#ff9f1c',
  muzzleFlashDistance: 0.05,
  muzzleFlashGlowColor: '#ffe7a6',
  muzzleFlashLength: 0.72,
  muzzleFlashLifetimeMs: 110,
  muzzleFlashLightDistance: 7.4,
  muzzleFlashLightIntensity: 2.2,
  muzzleFlashSecondaryColor: '#ff6b00',
  muzzleFlashSize: 0.3,
  muzzleFlashSparkColor: '#fff7da',
  tracerColor: '#ffd08a',
  tracerGlowColor: '#ffe6b8',
  tracerGlowThickness: 0.18,
  tracerLifetimeMs: 0,
  tracerThickness: 0.1,
  tracerTipColor: '#fff4d8',
  tracerTipSize: 0.08,
}

export const ROCKET_PROJECTILE_CONFIG: Omit<
  WeaponProjectileSpawn,
  'damage' | 'direction' | 'maxDistance' | 'position'
> = {
  blastRadius: 4.6,
  color: '#ff7b00',
  explosionAccentColor: '#fff4d0',
  explosionColor: '#ff8c42',
  explosionGlowColor: '#ffd19a',
  explosionLifetimeMs: 200,
  explosionLightDistance: 8.4,
  explosionLightIntensity: 5.2,
  explosionRingColor: '#ffdca8',
  explosionRingSize: 4.6,
  explosionSparkColor: '#ffe8bd',
  explosionSize: 3.1,
  glowColor: '#ffd18c',
  size: 0.22,
  speed: 42,
  trailAccentColor: '#fff1cf',
  trailColor: '#ffb347',
  trailLength: 1.1,
  trailPulseSize: 0.36,
  trailSize: 0.19,
  trailTipColor: '#fff8dc',
}

export const ROCKET_LAUNCHER_DEFINITION: WeaponDefinition = {
  cooldownSeconds: 0.66,
  damage: 120,
  displayName: 'Rocket Launcher',
  fireType: 'projectile',
  id: 'rocketLauncher',
  maxDistance: 120,
  visuals: ROCKET_LAUNCHER_VISUALS,
}
